# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.12.0  # check latest version
    hooks:
    -   id: black
        args: ["--line-length", "120"]
-   repo: https://github.com/PyCQA/isort
    rev: 7.0.0  # check latest version
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "120"]
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0   # check latest release
    hooks:
    -   id: flake8
        args: ["--max-line-length=120"]
        additional_dependencies:
            - flake8-bugbear
            - flake8-comprehensions
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1   # check latest release
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
